### ISSUE TITLE
vpc_id is removed in Terraform AWS Provider v2.0.0

### ISSUE THREAD

**Issue by michaa76** [traveloka/terraform-aws-private-route53-zone#5]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Terraform AWS Provider Version

```
Terraform v0.11.10
+ provider.aws v2.0.0
+ provider.null v2.1.0
```

### Affected Resource(s)

* aws_route53_zone

### Terraform Configuration Files

```hcl
module "private_route53_zone" {
  source  = "traveloka/private-route53-zone/aws"
  version = "0.2.0"
}
```

### Actual Behavior

```
"vpc_id": [REMOVED] use 'vpc' configuration block instead
```

### Steps to Reproduce

1. `terraform apply`

### References

* https://www.terraform.io/docs/providers/aws/guides/version-2-upgrade.html#resource-aws_route53_zone
* https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#200-february-27-2019
* https://github.com/terraform-providers/terraform-provider-aws/pull/7695
* https://www.terraform.io/docs/providers/aws/r/route53_zone.html

**Comment by igoratencompass** [comment]
Have you tried to modify your resource as the docs say https://www.terraform.io/docs/providers/aws/r/route53_zone.html:

```
resource "aws_route53_zone" "private" {
  name = "example.com"

  vpc {
    vpc_id = "${aws_vpc.example.id}"
  }
}
```
